### ISSUE TITLE
Spec

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/esci-web#1]
0.1.8

Spec for main menu component of esci web, Geoff, 24 Aug 2020

Current version (0.1.8) is a very good start.

**Control panel**
Buttons not so high, not so spaced, font a bit smaller (about the size of ‘Tails’ and ‘Lines’ in Normal tab of distributions). Smallen the buttons vertically to make room for pic—see below.

List of buttons in order:
    dances beta
    distributions beta
    _d_ picture beta  <_d_ in italics>
    precision for planning (in development)
    see r (in development)  <_r_ in italics>

The preview picture when mouse hovers over button is great. Current pictures are fine. Let’s have just the display area in pictures, i.e. don’t include the control panel at left. No title, no wide green border area.

We need to consider what happens when total screen area is smaller. At present, shifting the bottom border UP works fine, with a scroll bar appearing at right when a critical screen height is reached. Moving the right border to LEFT causes: (i) text in RH display area to reformat, then (ii) RH display stuff is truncated, so becomes hidden. No scroll bar appears at bottom—which is fine; we should simply design for a smallish screen, and have pictures to left, text to right.

Can we try having preview pictures in the control area at left? Either:
(i)	Pic appears immediately below the button in question, other lower buttons temporarily shifting down below pic, or
(ii)	Pic appears below the 5 buttons (Would we need a title for the preview pic in this case? I’m hoping not.)

(i) might be better, if it’s works fast and is not too hard to do.

To make the preview pics less tall, maybe crop for distributions and, for dances and d picture, make the pic from a screen with bottom border moved up, so aspect ratio is changed, i.e. curves in d picture not so tall, in dances not so many means dropping. All this so a good-looking pic should fit in control panel display area.

**RH display area**
ITNS cover pic, about half the height and width of current (or even a bit less)—in the top left of area.
Overlay on cover pic, in box: ‘Second edition due 2021’ maybe on two or three lines.
To the right of the cover pic: Information about the first edition, and blog, at
				www.thenewstatistics.com

Underneath book cover pic, the esci logo, about half the height and width of current, or a bit less. To its right: ‘exploratory software for confidence intervals’—all lower case, blue

Underneath: esci software is in development for the second edition. There are two components:
esci in R, running in jamovi, for data analysis and great graphs with CIs, by Robert Calin-Jageman
esci web in javascript, for statistical dances and interactive graphical tools, by Gordon Moore
		Buttons at left go to the pages of esci web

**Comment by gfmoore** [comment]
Okay, so a first attempt at following specification.

I've not added in comments about any other editions at the moment till I get confirmation or further direction

**Comment by gdcumming** [comment]
0.1.8

Generally looks good and works well. Buttons and pics at left are nice.

Overlay of cover pic: Textbox saying 'Second edition due 2021'. Maybe a pale cream background colour to match background of whole page. Could be simply a rectangle with text horizontal, or maybe a single line of text, smaller font, narrow box at a slant. Or two lines of text but box at a slant. Or whatever you think looks restrained and ok.

**Comment by gfmoore** [comment]
Done?

**Comment by gdcumming** [comment]
0.1.11

Label on cover pic looks good

**Comment by gdcumming** [comment]
0.1.13

Looks good. Copes very well when window is smallened--nice! Closing
