### ISSUE TITLE
pfp tweaks

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/esci-web#10]
Gordon, Just had a great zoom with Bob. Herewith our decisions and preferences for pfp.

First, he and I agree that it looks fantastic and works extremely well. It's not only essential for Chapter 10, but is sure to be a much-used tool for researchers, in a world in which good, usable (especially visual) tools for the precision approach to planning are scarce.

1. Let's have the C% drop down, instead of the fixed 95%. It would be fine to have the same range of options as we have in 'dances'. Of course default should be 95%. That range: 50, 68, 80, 90, 95, 98, 99, 99.8, 99.9.

2. Target MoE. Let's have this adjustable in steps of .01, with values reported to 2 d.p. A change from the present.

3. rho, ditto. Reported to 2 d.p., as at present, and moving in steps of .01. (That might possibly fix the issue I opened yesterday about inconsistent N values?)

Otherwise, stick with what we have: targ MoE range .05 to 2.0; N going down to 2; little steps visible in the main N curves; the way the two tabs work together.

It will be interesting to see how it all works with the new C% possibilities, running from 50% to 99.9%, Are there other things that we'll have to double-check, or tweak, or... as a consequence? Let's find out!

**Comment by gfmoore** [comment]
I definitely am leaving this till Monday!!! 😆

**Comment by gfmoore** [comment]
Ok, done I think.
Haven't checked values yet. I ran out of time today. :(

**Comment by gfmoore** [comment]
Will need proper tips for CI (and text!)

**Comment by gdcumming** [comment]
1.1.5

This is great! For **two groups**, I've done lots of checking b'n your pfp web and my extended ESCI--which now goes the full range of rho, C%, and targ MoE, but without the small steps in targ MoE. Everything I tried agreed perfectly, for both 'on average' and 'with assurance'. Aren't we great!

**For Paired Design, on average,** I compared pfp web and my new expanded sledge-hammer Excel workbook, which covers all the myriad cases that pfp web also covers. Everything was matching perfectly, but I eventually found 5 cases in which your and my N values disagreed by 1. Usually 2 vs 3--neither of which anyone should consider using anyway! I tracked down that they were cases in which the calculated value shown in the vast lower table of sledge-hammer, which is a table of calculated MoE values, was shown as exact to 1 d.p. I.e. instead of most values, shown to 6 d.p. (very occasionally 5 or 4) which was the limit for the cell size, a value appeared as e.g. 0.4. So there was a tiny tiny tiny rounding disagreement b'n your and my calcs in those cases, maybe at d.p. number 15 or so? Let's keep that as our little secret; I'm not going to suggest any ridiculous fix. I don't know which value would be 'correct'. The cases:

C=50% (which no one will use):
rho   targ MoE
.19     0 .6
.64     0.4
.91    0.2
.96    0.2
.99    0.1

**Paired Design, with assurance**
Tried numerous combinations, looked for values in the s-h table that were displayed to only 1 or 2 d.p.--couldn't find any.
Everything checked out perfectly. As I say, aren't we great!

Sorry about overlooking how to display and set C%, and tips. I've run out of time now, hope to respond further in a while.

**Comment by gdcumming** [comment]
1.1.5

**Changes to control panel**

Remove '95%' from block of text at top, so now reads: 'Find the smallest _N_ that will give a CI with...'

Panel 1, both tabs: Replace '95' in first line with drop down box for _C_. So that line reads: 
'1 Target MoE of <box>% CI <targvalue>'

Remove new bottom panel (sorry!), both tabs

**Display**

Remove '95%' from caption under lower axis. Now to read: 'MoE of CI, in population... '

**Tips**

Panel 1, both tabs: As at present, but in the first line, the text "of <box>% CI" to have tip: 'Choose confidence level % for CI'

**Comment by gfmoore** [comment]
>> Remove '95%' from block of text at top, so now reads: 'Find the smallest N that will give a CI with...'

Done

>> Panel 1, both tabs: Replace '95' in first line with drop down box for C. So that line reads:
'1 Target MoE of % CI '

Done

>> Remove new bottom panel (sorry!), both tabs

done

>> Remove '95%' from caption under lower axis. Now to read: 'MoE of CI, in population... '

done

>> Panel 1, both tabs: As at present, but in the first line, the text "of % CI" to have tip: 'Choose confidence level % for CI'

I think I've done what you wanted.

**Comment by gdcumming** [comment]
1.1.6

Thanks, that all looks great. I was uncertain about how the first line in Panel 1 would work out. It's pretty good I think, but needs a clearer lead in to the final box with MoE value. Can we try it with "is" inserted between 'CI' and '<targvalue>' ?

Are we then ready to release the whole thing? And have a party? I'd better draft a blog post.

**Comment by gfmoore** [comment]
By the ? I assume you meant the text box with the value?

Done.

**Comment by gdcumming** [comment]
1.1.7

Great. (I didn't type '?' but something in <..> that must have confused the system...)
Closing...
