### ISSUE TITLE
No italics for rho

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/esci-web#11]
Sorry about this, but I've just noticed: 'rho', like all Greek letters used as statistical symbols, should _not_ be in italics--that's according to APA style, which needs to be our guide in all things. I don't know why, but it's very long established. That's in contrast to _M_, _s_, _N_, etc, which are always in italics.

So, I anxiously check back through the modules. I see that mu and sigma are non-italic, as they should be, in dances and distributions, phew! The issue doesn't arise in d picture or correlation.

In precision for planning, Paired Design tab, all the tips are correct, phew. Just one change: the rho to the left of the slider.

In dance r, again all the tips are correct. Panel 2: one rho to change. Panel 10, three rho's to change. In the lower display, when rho line displayed, the 'rho' on the lower axis needs to change.

Sorry about all that.

**Comment by gfmoore** [comment]
>> In precision for planning, Paired Design tab, all the tips are correct, phew. Just one change: the rho to the left of the slider.
done

>>Dance r Panel 2: one rho to change.
done

>>Dance r Panel 10, three rho's to change
Changed but increased font size slightly, perhaps too much? Also the _r_

>>the 'rho' on the lower axis needs to change.
Done

**Comment by gdcumming** [comment]
pfp 1.1.3  all ok now I think

dance r 1.1.3  Panel 2:  still one rho label to right of slider to change. (Sorry if I missed that one.)
Font sizes look good.

**Comment by gfmoore** [comment]
Fixed, but not given a new version number.

**Comment by gdcumming** [comment]
1.1.3
:-)   closing...
