### ISSUE TITLE
CIs in dance r when rho is extreme

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/esci-web#14]
I'm having great fun working on Chap 11, Correlation. 

One issue: taking a sample with rho = -1 or 1 is fine. But we should not try to calculate a CI. Sample r is always = rho. I think we should trap this case (rho = min or max) and not permit calc of CI. Maybe just report CI as [- , -] and Percent capturing rho as red -, i.e. what we see when Panel 7 is first opened, or after Clear.

**Comment by gfmoore** [comment]
Oops yet again I'm not getting an email notification. I'll get on to it tomorrow now.

**Comment by gfmoore** [comment]
Well, that was a lot harder than expected. Please be on the look out for unanticipated issues.

**Comment by gdcumming** [comment]
1.1.4
Thanks. Seems to work fine, on my limited playing so far. I'll close and keep playing...
