### ISSUE TITLE
Tweaks to tips in 'dances'

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/esci-web#15]
(also sent as an email)
Hi Gordon,

Just wanted to check in, see how you are going, and say that Bob and I continue to beaver away towards ed. 2. Bob has had a tough summer and then semester, always with piles of student and uni issues to sort out. A short respite coming up, then what *should* be a less overwhelming first semester next year. He has lots planned for upgrading esci jamovi, tho' the basics are there already. He also plans tweaks to our main site and how it works, so esci web and esci jamovi are as robust and easily used as possible.

I also have a few tiny things to request. None is crucial, but hopefully they are not tricky to do, even if tedious. They are all in dances.

1. I was a bit tricked by not being able to open both 8 (Capture of next mean) and 9 (Dance of the _p_ values) at once. Of course not, but I'd forgotten, so it might seem mysterious to a new user. Let's have, at the end of the current text in the tip for each of the first lines in Panels 8 and 9: ". Cannot have both 'Capture of next mean' and 'Dance of the _p_ values' visible at once."

2. Tip for first line in Panel 9: make _p_ italic, as in "Display dance of the _p_ values"

3. When tips are off, the tip for '[ ] ± MoE around µ' is visible, but it shouldn't be.

Thanks. I'll also post this message as a GitHub issue.

I do hope you are going well, maybe a bit more relaxed than when we were bouncing messages and esci web advances back and forth, day by day? And if you are looking for work that you've found something remunerative that you like.

All the best for Christmas,

Geoff

**Comment by gfmoore** [comment]
Done, I hope :)

**Comment by gdcumming** [comment]
Dances 1.1.2

Perfect, thanks Gordon!
Best of luck with finding interesting and remunerative work.
Meanwhile all the best to you and yours for a safe and relaxing Christmas,
Geoff
