### ISSUE TITLE
text colour and layout

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/esci-web#3]
0.1.8

Text. Too much and too uniform in blue I think. Let's try changing some to black, or a 90% not-quite-fully-intense black, i.e. dark grey--or whatever colour you advise. In buttons, make 'beta' and '(in prep)' in black. Right display panel: Top sentence black. Text beside logo blue, as now. Lower text: all black, except software names (esci, R, javascript, jamovi, esci web...). Is 'javascript' ok in l/c or should it be JavaScript? Or some different or fuller brief description of what it's built in?

Revised layout:

First line: newline after the second comma, second line maybe indented a bit

esci in R, running in jamovi, by Robert Calin-Jageman <make 'esci' at start a link>        
- for data analysis and great graphs with CIs

esci web in javascript, by Gordon Moore       
- for statistical dances and interactive graphical tools
- use buttons at left to go to the pages

**Comment by gfmoore** [comment]
>> except software names (esci, R, javascript, jamovi, esci web...).

and what colour should these be in? I've assumed blue.

I think it would be helpful to have a mock up when you do this sort of thing, I'm sort of guessing sometimes what you mean? Sadly I can't see what you are seeing!!
;)

Oh what link do you want for Bob's esci?

**Comment by gdcumming** [comment]
0.1.13

Sorry about ambiguity, etc. Looks good.

Link for esci: https://thenewstatistics.com/itns/esci/jesci/

Can we have the grey text in a darker grey? I just wanted to avoid fully-stark black. Something like an 80-90% grey, whatever that means.

First text also in grey: "Information about the first edition, and blog, at"

Shift ", by Robert Calin-Jageman" to the line above, to come after 'jamovi'

Remove comma after your name (I know, I know, I'm getting very close to the edge with such tiny stuff...!)

**Comment by gdcumming** [comment]
0.1.15

Great. Closing
