### ISSUE TITLE
tips

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/esci-web#4]
0.1.8

Tips smaller in height, as in other pages. 

Top line, LH display area: 4 tips to match those in other pages.

Tips on buttons: Can we have them to the right of the mouse pointer, for easier seeing of and clicking on other buttons

dances: Investigate sampling. See dance of the means, dance of the CIs, dance of the _p_ values, and other goodies. <maybe two lines of text?>

distributions: Investigate normal and Student _t_ distributions. Find areas and critical values.

_d_ picture: Investigate how values of Cohen's _d_ relate to distributions and areas.

precision for planning: Find _N_ required to achieve desired target precision.

correlation: See a number of scatter plots for any chosen correlation _r_.

dance _r_: Investigate sampling of correlation values. See scatter plots and dances.

**Comment by gfmoore** [comment]
>> Tips smaller in height, as in other pages.

>> Top line, LH display area: 4 tips to match those in other pages.

>> Tips on buttons: Can we have them to the right of the mouse pointer, for easier seeing of and clicking on other buttons

The tips code hadn't been updated as I was waiting for the tips. So I've ignored these comments (for now)

Anyway implemented.

**Comment by gdcumming** [comment]
0.1.13

Look good. One glitch: tips don't seem to turn off when '?' clicked off.

**Comment by gfmoore** [comment]
Uhmm, seems I lost the disable line, fixed and I'm checking the other modules.

**Comment by gdcumming** [comment]
0.1.15

Great. Closing
