### ISSUE TITLE
Remove 2 links, for Release 2

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/esci-web#5]
0.1.15

Click 'dance r' button and get a message that there's no github there. Fine. (Or have some other message. "Watch this space..."?)

For the 'correlation' and 'precision for planning' buttons we need something similar, rather than an in-development page, before we do Release 2.

**Comment by gfmoore** [comment]
Basic In Development page added. It will satisfice for now I hope.

**Comment by gfmoore** [comment]
Well that didn't work!!!

**Comment by gfmoore** [comment]
Well try this one instead. You might need to shift refresh a couple of times!!

**Comment by gdcumming** [comment]
0.1.17 (main menu)  0.0.6 (correlation)

Neat message is there for 'precision for planning' and 'dance r'. Good.
But for 'correlation' I go to 0.0.6 in-development version, no matter how much reloading I do.

**Comment by gfmoore** [comment]
You might need to clear the cache in your browser, be careful not to clear anything else otherwise you end up re-entering a million usernames passwords, and for all time, not just last week.

I'll check it out though.

⁣Regards,

Gordon Moore
gm@gordonmoore.co.uk​

**Comment by gfmoore** [comment]
0.0.6 is the latest version???

regards,

Gordon Moore
gm@gordonmoore.co.uk

On 31/08/2020 00:21:23, Geoff Cumming <notifications@github.com> wrote:
0.1.17 (main menu) 0.0.6 (correlation)
Neat message is there for 'precision for planning' and 'dance r'. Good.
But for 'correlation' I go to 0.0.6 in-development version, no matter how much reloading I do.

**Comment by gdcumming** [comment]
0.1.17 (main menu) 0.0.7 (correlation)

For the 'correlation' button in Main Menu, I'm still sent to the in-development version of 'correlation', not the 'in development, coming soon' message. Yesterday it was the 0.0.6 version, this morning the 0.0.7 version.

I've tried on a different computer and our ipad, which I don't think I have before used with Main Menu. Same thing.

**Comment by gfmoore** [comment]
Ahhh, sorry. I didn't realise you also meant correlation as well. I'll sort it later.

⁣Regards,

Gordon Moore
gm@gordonmoore.co.uk​

**Comment by gfmoore** [comment]
Done

regards,

Gordon Moore
gm@gordonmoore.co.uk

On 01/09/2020 08:16:54, Gordon Moore <gordonfmoore@gmail.com> wrote:
Ahhh, sorry. I didn't realise you also meant correlation as well. I'll sort it later.


Regards,


Gordon Moore

gm@gordonmoore.co.uk
On 1 Sep 2020, at 00:13, Geoff Cumming <notifications@github.com [mailto:notifications@github.com]> wrote:
0.1.17 (main menu) 0.0.7 (correlation)
For the 'correlation' button in Main Menu, I'm still sent to the in-development version of 'correlation', not the 'in development, coming soon' message. Yesterday it was the 0.0.6 version, this morning the 0.0.7 version.
I've tried on a different computer and our ipad, which I don't think I have before used with Main Menu. Same thing.

**Comment by gdcumming** [comment]
0.1.18

Great. I believe we're ready to go with Release 2, as soon as we have a link at our home website. Closing
