### ISSUE TITLE
Remove tips, top line, each page

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/esci-web#6]
1.0.2

I love all this--now 4 components out to the world, and all linked nicely to our main site, and the esci web main menu.

The only tiny thing I've noticed is that in the top line for each component (and for Main Menu), 'esci web' and 'component name' each have a tip with a link to thenewstatistics.com. But there are no such links.

Given that we have a link just below to 'Home', and a link to thenewstatistics.com at the very bottom of each control panel, I suggest it would be best to remove those two tips from the top line of each page.

**Comment by gfmoore** [comment]
😄 Never even noticed this, but now done for all components.

**Comment by gdcumming** [comment]
Thanks. I confess I'd totally forgotten...
