### ISSUE TITLE
pfp Paired Design, erratic N

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/esci-web#7]
1.1.1

Here's a weird and frustrating one, I'm afraid. (Tho' I have a suggestion at the end...)

I first struck it for this case:

Paired Design, rho = .60, targ MoE = 0.20. N = 80 is correct. But after playing with the rho slider for a bit, I returned to rho = 60 and found N values on the curve to be incorrect, specifically N = 79 was shown for targ MoE = 0.20. N values were also out by 1 for some other values of rho and targ MoE.

I've been able to play some more, return to rho = .60 and see N = 80 again. Then play some more, chiefly with the rho slider, using thumbnail and/or nudge buttons, and see 79.

But I haven't found any sure-fire way to get 79, or to get back to 80. 

Also, sometimes but not always the rho value on the slider (just above the thumbnail) disagrees with the value reported just to the right of the nudge buttons. They differ, if at all, by .01. (e.g., .59 and .60) Again, I haven't found a sure-fire way to create or escape from that disagreement. Haphazard playing with the slider can unpredictably (to me, anyway) produce or recover from the problem.

Hmmmm. I'm wondering whether, behind the scenes, rho values change by .005 (as maybe we talked about a while back), but values are shown only to .01? That could conceivably cause the behaviour I'm seeing? Perhaps restricting rho to steps of .01 would fix it? (It's on the list to discuss with Bob, in relation to the step size for targ MoE. I'm inclined to favour .01 steps there as well. I hope to be reporting soon.)

**Comment by gfmoore** [comment]
Good catch. Very impressive deduction Mr Holmes 😃   Indeed the slider was going up by 0.005 and the nudge arrows by 0.01, so if it got caught in an intermediate value you couldn't get back to a 0.01 multiple. I have now made the slider go up by 0.01 Sorry for the trouble caused.

**Comment by gfmoore** [comment]
Uhmm now that the app is rationalised into one repository I now have the issue of versioning. I think all I can do is apply version numbers individually to each app.

**Comment by gdcumming** [comment]
0.1.2
Great--closing...
